# Generated by Django 4.2.5 on 2023-10-17 23:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catedraticos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('DPI', models.CharField(max_length=13, unique=True, validators=[django.core.validators.RegexValidator(message='El DPI debe contener exactamente 13 dígitos numéricos.', regex='^[0-9]{13}$')])),
                ('password', models.CharField(max_length=15)),
            ],
            options={
                'verbose_name': 'Catedratico',
                'verbose_name_plural': 'Catedraticos',
                'db_table': 'Catedraticos',
            },
        ),
        migrations.CreateModel(
            name='Estudiantes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('dpi', models.CharField(max_length=13, unique=True, validators=[django.core.validators.RegexValidator(message='El DPI debe contener exactamente 13 dígitos numéricos.', regex='^[0-9]{13}$')])),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('telefono', models.IntegerField()),
                ('usuario', models.CharField(max_length=10, unique=True)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('contraseña', models.CharField()),
                ('imagen', models.ImageField(upload_to='Estudiantes/')),
                ('intentos_fallidos', models.IntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Estudiante',
                'verbose_name_plural': 'Estudiantes',
                'db_table': 'Estudiantes',
            },
        ),
    ]
