# Generated by Django 4.2.5 on 2023-10-19 19:41

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Catedraticos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('DPI', models.CharField(max_length=13, unique=True, validators=[django.core.validators.RegexValidator(message='El DPI debe contener exactamente 13 dígitos numéricos.', regex='^[0-9]{13}$')])),
                ('password', models.CharField(max_length=15)),
            ],
            options={
                'verbose_name': 'Catedratico',
                'verbose_name_plural': 'Catedraticos',
                'db_table': 'Catedraticos',
            },
        ),
        migrations.CreateModel(
            name='Estudiantes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='nombre', max_length=150)),
                ('last_name', models.CharField(default='Apellidos', max_length=150)),
                ('username', models.CharField(default=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL), max_length=150)),
                ('email', models.EmailField(default='direccion@gmail.com', max_length=150)),
                ('DPI', models.CharField(default='0', max_length=13)),
                ('telefono', models.CharField(default='0', max_length=8)),
                ('fecha_nacimiento', models.DateField()),
                ('profile_image', models.ImageField(upload_to='Estudiantes/')),
                ('login_attempts', models.IntegerField(default=0)),
                ('active_account', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Estudiante',
                'verbose_name_plural': 'Estudiantes',
                'db_table': 'Estudiantes',
                'ordering': ['id'],
            },
        ),
    ]
