# Generated by Django 4.2.5 on 2023-10-16 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0003_alter_estudiantes_contraseña'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiantes',
            name='imagen',
            field=models.ImageField(upload_to='media/Estudiantes/'),
        ),
    ]
