# Generated by Django 4.2.5 on 2023-10-16 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0004_alter_estudiantes_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiantes',
            name='imagen',
            field=models.ImageField(upload_to='Estudiantes/'),
        ),
    ]
